services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postresql+psycopg://rag_user:rag_password:5432/rag_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      volumes:
        - ./app:/app/app
      
volumes:
  pgdata: